NAME = zombie

SRCS = zombie.cpp

HEADERS = zom.hpp

CC = c++;


FLAGS = -Wall -Wextra -Werror -std=c++98 -O3

all:$(NAME)

OBJS = $(SRCS:%.c = %.o)

$(NAME): $(OBJS) $(HEADERS)
	$(CC) $(SRCS) $(FLAGS) -o (NAME)